version: '3.8'
services:
  qvantum-relay:
    image: sciohub/qvantum-relay:staging
    container_name: qvantum-relay
    restart: unless-stopped
    ports:
      - 50200:5000
    volumes:
      - /etc/letsencrypt/live/${HOST}/privkey.pem:/etc/letsencrypt/live/${HOST}/privkey.pem
      - /etc/letsencrypt/live/${HOST}/cert.pem:/etc/letsencrypt/live/${HOST}/cert.pem
      - /etc/letsencrypt/live/${HOST}/chain.pem:/etc/letsencrypt/live/${HOST}/chain.pem
    env_file:
      - .env
      